# Generated by Django 2.1 on 2020-05-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Signup', 'verbose_name_plural': 'Signup'},
        ),
    ]
