# Generated by Django 2.1.5 on 2020-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200529_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Field of study', 'verbose_name_plural': 'Fields of study'},
        ),
    ]
